server:
  port: 8040

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: notifications@einsurance.test
    password: change-me
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

pdf:
  company-name: E-Insurance Co.
  output-path: ./generated-pdfs

services:
  user-service:
    url: http://localhost:8222/api/users
  policy-service:
    url: http://localhost:8222/api/policies
  claims-service:
    url: http://localhost:8222/api/claims

keycloak:
  auth-server-url: http://localhost:9098
  realm: einsurance-realm

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
