server:
  port: 8060

spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    user: postgres
    password: postgres

stripe:
  secret-key: sk_test_change-me
  publishable-key: pk_test_change-me
  webhook-secret: whsec_change-me
  success-url: http://localhost:3000/payment/success
  cancel-url: http://localhost:3000/payment/cancel

keycloak:
  auth-server-url: http://localhost:9098
  realm: einsurance-realm

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
